# safelist
branches:
  only:
    - master
    - dev
jobs:
  include:
    - stage: Test and lint âœ…
      before_install:
        - npm i -g npm@6.14.6
        - npm i -g yarn@1.22.10
      language: node_js
      node_js: 12.18.4
      install: yarn
      script: yarn lint
    - stage: Build Android ðŸ¤–
      before_install:
        - sudo apt-get install build-essential checkinstall && sudo apt-get install libssl-dev
        - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
        - source ~/.profile
        - nvm install 12.18.4
        - npm i -g yarn@1.22.10
      language: android
      android:
        components:
          - tools
          - platform-tools
          # - build-tools-26.0.2
          - build-tools-27.0.3
          # - android-26
          - android-27
          - addon-google_apis-google-26
      sudo: true
      install:
        - yarn install
      script:
        - cd /usr/local/android-sdk/tools/bin
        - yes | ./sdkmanager --update
        - cd - && cd android && ./gradlew assembleRelease -x bundleReleaseJsAndAssets && cd ..
